# Docker Compose configuration for Smart CV Evaluator

services:
  smart-cv-evaluator:
    build: .
    container_name: smart-cv-evaluator
    ports:
      - "8501:8501"
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cv-network

  # Optional: Add Ollama service if you want to run it in Docker
  # Uncomment the following if you want to run Ollama in Docker
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama
  #   environment:
  #     - OLLAMA_HOST=0.0.0.0
  #   restart: unless-stopped
  #   networks:
  #     - cv-network

networks:
  cv-network:
    driver: bridge

# Uncomment if using Ollama service
# volumes:
#   ollama_data:
